mutation CreateStudent(
  $admissionNumber: String!
  $name: String!
  $course: String!
  $year: Int!
  $dateOfBirth: Date!
  $email: String!
  $mobileNumber: String!
  $gender: String!
  $address: String!
  $photoUrl: String
) @auth(level: NO_ACCESS) {
  key: student_insert(
    data: {
      admissionNumber: $admissionNumber
      name: $name
      course: $course
      year: $year
      dateOfBirth: $dateOfBirth
      email: $email
      mobileNumber: $mobileNumber
      gender: $gender
      address: $address
      photoUrl: $photoUrl
      updatedAt_expr: "request.time"
    }
  )
}

mutation UpdateStudent(
  $id: UUID!
  $name: String!
  $course: String!
  $year: Int!
  $dateOfBirth: Date!
  $email: String!
  $mobileNumber: String!
  $gender: String!
  $address: String!
  $photoUrl: String
) @auth(level: NO_ACCESS) {
  key: student_update(
    id: $id
    data: {
      name: $name
      course: $course
      year: $year
      dateOfBirth: $dateOfBirth
      email: $email
      mobileNumber: $mobileNumber
      gender: $gender
      address: $address
      photoUrl: $photoUrl
      updatedAt_expr: "request.time"
    }
  )
}

mutation DeleteStudent($id: UUID!) @auth(level: NO_ACCESS) {
  key: student_delete(id: $id)
}
