query ListStudents @auth(level: NO_ACCESS) {
  students(orderBy: [{ createdAt: DESC }]) {
    id
    admissionNumber
    name
    course
    year
    dateOfBirth
    email
    mobileNumber
    gender
    address
    photoUrl
    createdAt
    updatedAt
  }
}

query SearchStudents($query: String!) @auth(level: NO_ACCESS) {
  students(
    orderBy: [{ createdAt: DESC }]
    where: {
      _or: [
        { name: { contains: $query } }
        { course: { contains: $query } }
        { admissionNumber: { contains: $query } }
        { email: { contains: $query } }
      ]
    }
  ) {
    id
    admissionNumber
    name
    course
    year
    dateOfBirth
    email
    mobileNumber
    gender
    address
    photoUrl
    createdAt
    updatedAt
  }
}

query GetStudentById($id: UUID!) @auth(level: NO_ACCESS) {
  student(id: $id) {
    id
    admissionNumber
    name
    course
    year
    dateOfBirth
    email
    mobileNumber
    gender
    address
    photoUrl
    createdAt
    updatedAt
  }
}
